.TH "drivers/TempSensor/Adafruit_Python_MCP9808/Adafruit_MCP9808/__init__.py" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drivers/TempSensor/Adafruit_Python_MCP9808/Adafruit_MCP9808/__init__.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAdafruit_MCP9808\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
