.TH "lib/messages/spa Directory Reference" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/messages/spa Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBspa_courier\&.h\fP"
.br
.ti -1c
.RI "file \fBspa_data\&.h\fP"
.br
.ti -1c
.RI "file \fBsubscription_reply\&.h\fP"
.br
.ti -1c
.RI "file \fBsubscription_request\&.h\fP"
.br
.in -1c
