.TH "lib/socket Directory Reference" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/socket Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclientSocket\&.cpp\fP"
.br
.ti -1c
.RI "file \fBclientSocket\&.hpp\fP"
.br
.ti -1c
.RI "file \fBserverSocket\&.cpp\fP"
.br
.ti -1c
.RI "file \fBserverSocket\&.hpp\fP"
.br
.in -1c
