.TH "drivers/TempSensor/Adafruit_Python_MCP9808 Directory Reference" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drivers/TempSensor/Adafruit_Python_MCP9808 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAdafruit_MCP9808\fP"
.br
.ti -1c
.RI "directory \fBexamples\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBez_setup\&.py\fP"
.br
.ti -1c
.RI "file \fBsetup\&.py\fP"
.br
.in -1c
