.TH "drivers/TempSensor Directory Reference" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drivers/TempSensor Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAdafruit_Python_MCP9808\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBTempSensor\&.cpp\fP"
.br
.in -1c
