.TH "Adafruit_MCP9808.MCP9808" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Adafruit_MCP9808.MCP9808
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMCP9808\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBMCP9808_I2CADDR_DEFAULT\fP = 0x18"
.br
.ti -1c
.RI "int \fBMCP9808_REG_CONFIG\fP = 0x01"
.br
.ti -1c
.RI "int \fBMCP9808_REG_UPPER_TEMP\fP = 0x02"
.br
.ti -1c
.RI "int \fBMCP9808_REG_LOWER_TEMP\fP = 0x03"
.br
.ti -1c
.RI "int \fBMCP9808_REG_CRIT_TEMP\fP = 0x04"
.br
.ti -1c
.RI "int \fBMCP9808_REG_AMBIENT_TEMP\fP = 0x05"
.br
.ti -1c
.RI "int \fBMCP9808_REG_MANUF_ID\fP = 0x06"
.br
.ti -1c
.RI "int \fBMCP9808_REG_DEVICE_ID\fP = 0x07"
.br
.ti -1c
.RI "int \fBMCP9808_REG_CONFIG_SHUTDOWN\fP = 0x0100"
.br
.ti -1c
.RI "int \fBMCP9808_REG_CONFIG_CRITLOCKED\fP = 0x0080"
.br
.ti -1c
.RI "int \fBMCP9808_REG_CONFIG_WINLOCKED\fP = 0x0040"
.br
.ti -1c
.RI "int \fBMCP9808_REG_CONFIG_INTCLR\fP = 0x0020"
.br
.ti -1c
.RI "int \fBMCP9808_REG_CONFIG_ALERTSTAT\fP = 0x0010"
.br
.ti -1c
.RI "int \fBMCP9808_REG_CONFIG_ALERTCTRL\fP = 0x0008"
.br
.ti -1c
.RI "int \fBMCP9808_REG_CONFIG_ALERTSEL\fP = 0x0002"
.br
.ti -1c
.RI "int \fBMCP9808_REG_CONFIG_ALERTPOL\fP = 0x0002"
.br
.ti -1c
.RI "int \fBMCP9808_REG_CONFIG_ALERTMODE\fP = 0x0001"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int Adafruit_MCP9808\&.MCP9808\&.MCP9808_I2CADDR_DEFAULT = 0x18"

.SS "int Adafruit_MCP9808\&.MCP9808\&.MCP9808_REG_AMBIENT_TEMP = 0x05"

.SS "int Adafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CONFIG = 0x01"

.SS "int Adafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CONFIG_ALERTCTRL = 0x0008"

.SS "int Adafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CONFIG_ALERTMODE = 0x0001"

.SS "int Adafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CONFIG_ALERTPOL = 0x0002"

.SS "int Adafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CONFIG_ALERTSEL = 0x0002"

.SS "int Adafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CONFIG_ALERTSTAT = 0x0010"

.SS "int Adafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CONFIG_CRITLOCKED = 0x0080"

.SS "int Adafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CONFIG_INTCLR = 0x0020"

.SS "int Adafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CONFIG_SHUTDOWN = 0x0100"

.SS "int Adafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CONFIG_WINLOCKED = 0x0040"

.SS "int Adafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CRIT_TEMP = 0x04"

.SS "int Adafruit_MCP9808\&.MCP9808\&.MCP9808_REG_DEVICE_ID = 0x07"

.SS "int Adafruit_MCP9808\&.MCP9808\&.MCP9808_REG_LOWER_TEMP = 0x03"

.SS "int Adafruit_MCP9808\&.MCP9808\&.MCP9808_REG_MANUF_ID = 0x06"

.SS "int Adafruit_MCP9808\&.MCP9808\&.MCP9808_REG_UPPER_TEMP = 0x02"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
