.TH "ComponentInfo" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ComponentInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <component_list\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBComponentInfo\fP (\fBLogicalAddress\fP la, bool h)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLogicalAddress\fP \fBaddress\fP"
.br
.ti -1c
.RI "bool \fBhealthy\fP = true"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ComponentInfo::ComponentInfo (\fBLogicalAddress\fP la, bool h)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBLogicalAddress\fP ComponentInfo::address"

.SS "bool ComponentInfo::healthy = true"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
