.TH "COMP_NAME" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
COMP_NAME
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCOMP_NAME\fP (std::shared_ptr< \fBSpaCommunicator\fP > com=nullptr)"
.br
.ti -1c
.RI "void \fBhandleSpaData\fP (\fBSpaMessage\fP *message)"
.br
.ti -1c
.RI "void \fBsendData\fP (\fBLogicalAddress\fP destination)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "COMP_NAME::COMP_NAME (std::shared_ptr< \fBSpaCommunicator\fP > com = \fCnullptr\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void COMP_NAME::handleSpaData (\fBSpaMessage\fP * message)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBComponent\fP\&.
.SS "void COMP_NAME::init ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBComponent\fP\&.
.SS "void COMP_NAME::sendData (\fBLogicalAddress\fP destination)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBComponent\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
