.TH "ComponentList" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ComponentList
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <component_list\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBComponentList\fP ()"
.br
.ti -1c
.RI "\fBComponentList\fP (\fBLogicalAddress\fP l)"
.br
.ti -1c
.RI "void \fBadd\fP (\fBLogicalAddress\fP la)"
.br
.ti -1c
.RI "\fBLogicalAddress\fP \fBgetAddress\fP (int i)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBComponentInfo\fP > \fBlist\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ComponentList::ComponentList ()\fC [inline]\fP"

.SS "ComponentList::ComponentList (\fBLogicalAddress\fP l)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ComponentList::add (\fBLogicalAddress\fP la)\fC [inline]\fP"

.SS "\fBLogicalAddress\fP ComponentList::getAddress (int i)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBComponentInfo\fP> ComponentList::list\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
