.TH "cubiumClientSocket_t" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cubiumClientSocket_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <clientSocket\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBsock\fP"
.br
.ti -1c
.RI "uint32_t \fBnBytesRecv\fP"
.br
.ti -1c
.RI "uint32_t \fBlength\fP"
.br
.ti -1c
.RI "struct sockaddr_in \fBserver\fP"
.br
.ti -1c
.RI "struct sockaddr_in \fBfrom\fP"
.br
.ti -1c
.RI "struct hostent * \fBhp\fP"
.br
.ti -1c
.RI "char \fBbuf\fP [256]"
.br
.ti -1c
.RI "bool \fBisBuf\fP = false"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char cubiumClientSocket_t::buf[256]"

.SS "struct sockaddr_in cubiumClientSocket_t::from"

.SS "struct hostent* cubiumClientSocket_t::hp"

.SS "bool cubiumClientSocket_t::isBuf = false"

.SS "uint32_t cubiumClientSocket_t::length"

.SS "uint32_t cubiumClientSocket_t::nBytesRecv"

.SS "struct sockaddr_in cubiumClientSocket_t::server"

.SS "uint32_t cubiumClientSocket_t::sock"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
