.TH "drivers/demo_addresses.hpp" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drivers/demo_addresses.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <logical_address\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBLogicalAddress\fP \fBla_LSM\fP (1, 0)"
.br
.ti -1c
.RI "const \fBLogicalAddress\fP \fBla_TempSensor\fP (1, 1)"
.br
.ti -1c
.RI "const \fBLogicalAddress\fP \fBla_CB\fP (1, 2)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const \fBLogicalAddress\fP la_CB(1, 2)"

.SS "const \fBLogicalAddress\fP la_LSM(1, 0)"

.SS "const \fBLogicalAddress\fP la_TempSensor(1, 1)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
