.TH "drivers/TempSensor/Adafruit_Python_MCP9808/ez_setup.py" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drivers/TempSensor/Adafruit_Python_MCP9808/ez_setup.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBez_setup\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBez_setup\&._python_cmd\fP (args)"
.br
.ti -1c
.RI "def \fBez_setup\&._install\fP (archive_filename, install_args=())"
.br
.ti -1c
.RI "def \fBez_setup\&._build_egg\fP (egg, archive_filename, to_dir)"
.br
.ti -1c
.RI "def \fBez_setup\&.get_zip_class\fP ()"
.br
.ti -1c
.RI "def \fBez_setup\&.archive_context\fP (filename)"
.br
.ti -1c
.RI "def \fBez_setup\&._do_download\fP (version, download_base, to_dir, download_delay)"
.br
.ti -1c
.RI "def \fBez_setup\&.use_setuptools\fP (version=DEFAULT_VERSION, download_base=DEFAULT_URL, to_dir=os\&.curdir, download_delay=15)"
.br
.ti -1c
.RI "def \fBez_setup\&._clean_check\fP (cmd, target)"
.br
.ti -1c
.RI "def \fBez_setup\&.download_file_powershell\fP (url, target)"
.br
.ti -1c
.RI "def \fBez_setup\&.has_powershell\fP ()"
.br
.ti -1c
.RI "def \fBez_setup\&.download_file_curl\fP (url, target)"
.br
.ti -1c
.RI "def \fBez_setup\&.has_curl\fP ()"
.br
.ti -1c
.RI "def \fBez_setup\&.download_file_wget\fP (url, target)"
.br
.ti -1c
.RI "def \fBez_setup\&.has_wget\fP ()"
.br
.ti -1c
.RI "def \fBez_setup\&.download_file_insecure\fP (url, target)"
.br
.ti -1c
.RI "def \fBez_setup\&.get_best_downloader\fP ()"
.br
.ti -1c
.RI "def \fBez_setup\&.download_setuptools\fP (version=DEFAULT_VERSION, download_base=DEFAULT_URL, to_dir=os\&.curdir, delay=15, downloader_factory=get_best_downloader)"
.br
.ti -1c
.RI "def \fBez_setup\&._build_install_args\fP (options)"
.br
.ti -1c
.RI "def \fBez_setup\&._parse_args\fP ()"
.br
.ti -1c
.RI "def \fBez_setup\&.main\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBez_setup\&.USER_SITE\fP = None"
.br
.ti -1c
.RI "string \fBez_setup\&.DEFAULT_VERSION\fP = '3\&.5\&.1'"
.br
.ti -1c
.RI "string \fBez_setup\&.DEFAULT_URL\fP = 'https://pypi\&.python\&.org/packages/source/s/setuptools/'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
