.TH "lib/local_subnet_manager.hpp" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/local_subnet_manager.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'component_list\&.hpp'\fP
.br
\fC#include 'subnet_manager\&.hpp'\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLocalSubnetManager\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBLSM_messageCallback\fP (std::shared_ptr< \fBLocalSubnetManager\fP > lsm, \fBcubiumServerSocket_t\fP *sock)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void LSM_messageCallback (std::shared_ptr< \fBLocalSubnetManager\fP > lsm, \fBcubiumServerSocket_t\fP * sock)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
