.TH "lib/local_communicator.hpp" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/local_communicator.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'physical_communicator\&.hpp'\fP
.br
\fC#include 'routing_table\&.hpp'\fP
.br
\fC#include 'socket/clientSocket\&.hpp'\fP
.br
\fC#include 'socket/serverSocket\&.hpp'\fP
.br
\fC#include 'spa_message\&.h'\fP
.br
\fC#include <functional>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <map>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLocalCommunicator\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSERVER\fP   '127\&.0\&.0\&.1'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SERVER   '127\&.0\&.0\&.1'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
