.TH "LocalAck" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LocalAck
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <local_ack\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocalAck\fP (uint8_t version, uint8_t priority, \fBLogicalAddress\fP destination, \fBLogicalAddress\fP source, uint16_t flags, uint16_t sourcePort, uint8_t \fBstatus\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLocalSpaMessage\fP \fBlocalSpaMessage\fP"
.br
.ti -1c
.RI "uint8_t \fBstatus\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LocalAck::LocalAck (uint8_t version, uint8_t priority, \fBLogicalAddress\fP destination, \fBLogicalAddress\fP source, uint16_t flags, uint16_t sourcePort, uint8_t status)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBLocalSpaMessage\fP LocalAck::localSpaMessage"

.SS "uint8_t LocalAck::status"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
