.TH "LocalHello" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LocalHello
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <local_hello\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocalHello\fP (uint8_t version, uint8_t priority, \fBLogicalAddress\fP destination, \fBLogicalAddress\fP source, uint16_t flags, uint16_t sourcePort, uint64_t \fBuuid\fP, uint8_t \fBcomponentType\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLocalSpaMessage\fP \fBlocalSpaMessage\fP"
.br
.ti -1c
.RI "uint64_t \fBuuid\fP"
.br
.ti -1c
.RI "uint8_t \fBcomponentType\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LocalHello::LocalHello (uint8_t version, uint8_t priority, \fBLogicalAddress\fP destination, \fBLogicalAddress\fP source, uint16_t flags, uint16_t sourcePort, uint64_t uuid, uint8_t componentType)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "uint8_t LocalHello::componentType"

.SS "\fBLocalSpaMessage\fP LocalHello::localSpaMessage"

.SS "uint64_t LocalHello::uuid"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
