.TH "lib/local_communicator.cpp" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/local_communicator.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'local_communicator\&.hpp'\fP
.br
\fC#include 'messages/op_codes\&.h'\fP
.br
\fC#include 'messages/spa/spa_data\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
