.TH "lib/messages/local/local_spa_message.h" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/messages/local/local_spa_message.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <messages/spa_local_header\&.h>\fP
.br
\fC#include <spa_message\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBLocalSpaMessage\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
