.TH "lib/logical_address.cpp" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/logical_address.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'logical_address\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBLogicalAddress\fP &lhs, const \fBLogicalAddress\fP &rhs)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &o, \fBLogicalAddress\fP const &la)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & o, \fBLogicalAddress\fP const & la)"

.SS "bool operator== (const \fBLogicalAddress\fP & lhs, const \fBLogicalAddress\fP & rhs)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
