.TH "LogicalAddressCompare" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogicalAddressCompare
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logical_address\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBLogicalAddress\fP &lhs, const \fBLogicalAddress\fP &rhs) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool LogicalAddressCompare::operator() (const \fBLogicalAddress\fP & lhs, const \fBLogicalAddress\fP & rhs) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
