.TH "LogicalAddress" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogicalAddress
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logical_address\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogicalAddress\fP (uint16_t subId=0, uint16_t compId=0)"
.br
.ti -1c
.RI "bool \fBisOnSameSubnet\fP (\fBLogicalAddress\fP other)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBsubnetId\fP"
.br
.ti -1c
.RI "uint16_t \fBcomponentId\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LogicalAddress::LogicalAddress (uint16_t subId = \fC0\fP, uint16_t compId = \fC0\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool LogicalAddress::isOnSameSubnet (\fBLogicalAddress\fP other)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "uint16_t LogicalAddress::componentId"

.SS "uint16_t LogicalAddress::subnetId"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
