.TH "lib/logical_address.h" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/logical_address.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBLogicalAddress\fP"
.br
.ti -1c
.RI "struct \fBLogicalAddressCompare\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &o, const \fBLogicalAddress\fP &la)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBLogicalAddress\fP &lhs, const \fBLogicalAddress\fP &rhs)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & o, const \fBLogicalAddress\fP & la)"

.SS "bool operator== (const \fBLogicalAddress\fP & lhs, const \fBLogicalAddress\fP & rhs)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
