.TH "drivers/TempSensor/Adafruit_Python_MCP9808/Adafruit_MCP9808/MCP9808.py" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drivers/TempSensor/Adafruit_Python_MCP9808/Adafruit_MCP9808/MCP9808.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAdafruit_MCP9808\&.MCP9808\&.MCP9808\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAdafruit_MCP9808\&.MCP9808\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBAdafruit_MCP9808\&.MCP9808\&.MCP9808_I2CADDR_DEFAULT\fP = 0x18"
.br
.ti -1c
.RI "int \fBAdafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CONFIG\fP = 0x01"
.br
.ti -1c
.RI "int \fBAdafruit_MCP9808\&.MCP9808\&.MCP9808_REG_UPPER_TEMP\fP = 0x02"
.br
.ti -1c
.RI "int \fBAdafruit_MCP9808\&.MCP9808\&.MCP9808_REG_LOWER_TEMP\fP = 0x03"
.br
.ti -1c
.RI "int \fBAdafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CRIT_TEMP\fP = 0x04"
.br
.ti -1c
.RI "int \fBAdafruit_MCP9808\&.MCP9808\&.MCP9808_REG_AMBIENT_TEMP\fP = 0x05"
.br
.ti -1c
.RI "int \fBAdafruit_MCP9808\&.MCP9808\&.MCP9808_REG_MANUF_ID\fP = 0x06"
.br
.ti -1c
.RI "int \fBAdafruit_MCP9808\&.MCP9808\&.MCP9808_REG_DEVICE_ID\fP = 0x07"
.br
.ti -1c
.RI "int \fBAdafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CONFIG_SHUTDOWN\fP = 0x0100"
.br
.ti -1c
.RI "int \fBAdafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CONFIG_CRITLOCKED\fP = 0x0080"
.br
.ti -1c
.RI "int \fBAdafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CONFIG_WINLOCKED\fP = 0x0040"
.br
.ti -1c
.RI "int \fBAdafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CONFIG_INTCLR\fP = 0x0020"
.br
.ti -1c
.RI "int \fBAdafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CONFIG_ALERTSTAT\fP = 0x0010"
.br
.ti -1c
.RI "int \fBAdafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CONFIG_ALERTCTRL\fP = 0x0008"
.br
.ti -1c
.RI "int \fBAdafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CONFIG_ALERTSEL\fP = 0x0002"
.br
.ti -1c
.RI "int \fBAdafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CONFIG_ALERTPOL\fP = 0x0002"
.br
.ti -1c
.RI "int \fBAdafruit_MCP9808\&.MCP9808\&.MCP9808_REG_CONFIG_ALERTMODE\fP = 0x0001"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
