.TH "md_drivers_TempSensor_Adafruit_Python_MCP9808_README" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_drivers_TempSensor_Adafruit_Python_MCP9808_READMEAdafruit Python MCP9808 
 \- Python library for accessing the MCP9808 precision temperature sensor on a Raspberry Pi or Beaglebone Black\&.
.PP
Designed specifically to work with the Adafruit MCP9808 sensor ----> https://www.adafruit.com/product/1782
.PP
To install, first make sure some dependencies are available by running the following commands (on a Raspbian or Beaglebone Black Debian install):
.PP
.PP
.nf
sudo apt-get update
sudo apt-get install build-essential python-dev python-smbus
.fi
.PP
.PP
Then download the library by clicking the download zip link to the right and unzip the archive somewhere on your Raspberry Pi or Beaglebone Black\&. Then execute the following command in the directory of the library:
.PP
.PP
.nf
sudo python setup\&.py install
.fi
.PP
.PP
Make sure you have internet access on the device so it can download the required dependencies\&.
.PP
See examples of usage in the examples folder\&.
.PP
Adafruit invests time and resources providing this open source code, please support Adafruit and open-source hardware by purchasing products from Adafruit!
.PP
Written by Tony DiCola for Adafruit Industries\&. MIT license, all text above must be included in any redistribution 
