.TH "lib/messages/op_codes.h" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/messages/op_codes.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const uint8_t \fBop_LOCAL_HELLO\fP = 0x20"
.br
.ti -1c
.RI "const uint8_t \fBop_LOCAL_ACK\fP = 0x21"
.br
.ti -1c
.RI "const uint8_t \fBop_SPA_SUBSCRIPTION_REQUEST\fP = 0x46"
.br
.ti -1c
.RI "const uint8_t \fBop_SPA_SUBSCRIPTION_REPLY\fP = 0x47"
.br
.ti -1c
.RI "const uint8_t \fBop_SPA_DATA\fP = 0x74"
.br
.ti -1c
.RI "const uint8_t \fBop_SPA_COURIER\fP = 0x75"
.br
.ti -1c
.RI "const uint8_t \fBop_SPA_WRAPPED_GIFT\fP = 0x76"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const uint8_t op_LOCAL_ACK = 0x21"

.SS "const uint8_t op_LOCAL_HELLO = 0x20"

.SS "const uint8_t op_SPA_COURIER = 0x75"

.SS "const uint8_t op_SPA_DATA = 0x74"

.SS "const uint8_t op_SPA_SUBSCRIPTION_REPLY = 0x47"

.SS "const uint8_t op_SPA_SUBSCRIPTION_REQUEST = 0x46"

.SS "const uint8_t op_SPA_WRAPPED_GIFT = 0x76"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
