.TH "setup" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
setup
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBclassifiers\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBversion\fP"
.br
.ti -1c
.RI "\fBauthor\fP"
.br
.ti -1c
.RI "\fBauthor_email\fP"
.br
.ti -1c
.RI "\fBdescription\fP"
.br
.ti -1c
.RI "\fBlicense\fP"
.br
.ti -1c
.RI "\fBurl\fP"
.br
.ti -1c
.RI "\fBdependency_links\fP"
.br
.ti -1c
.RI "\fBinstall_requires\fP"
.br
.ti -1c
.RI "\fBpackages\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "setup\&.author"

.SS "setup\&.author_email"

.SS "setup\&.classifiers"
\fBInitial value:\fP
.PP
.nf
1 =  ['Development Status :: 4 - Beta',
2                'Operating System :: POSIX :: Linux',
3                'License :: OSI Approved :: MIT License',
4                'Intended Audience :: Developers',
5                'Programming Language :: Python :: 2\&.7',
6                'Programming Language :: Python :: 3',
7                'Topic :: Software Development',
8                'Topic :: System :: Hardware']
.fi
.SS "setup\&.dependency_links"

.SS "setup\&.description"

.SS "setup\&.install_requires"

.SS "setup\&.license"

.SS "setup\&.name"

.SS "setup\&.packages"

.SS "setup\&.url"

.SS "setup\&.version"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
