.TH "drivers/TempSensor/Adafruit_Python_MCP9808/setup.py" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drivers/TempSensor/Adafruit_Python_MCP9808/setup.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsetup\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBsetup\&.classifiers\fP"
.br
.ti -1c
.RI "\fBsetup\&.name\fP"
.br
.ti -1c
.RI "\fBsetup\&.version\fP"
.br
.ti -1c
.RI "\fBsetup\&.author\fP"
.br
.ti -1c
.RI "\fBsetup\&.author_email\fP"
.br
.ti -1c
.RI "\fBsetup\&.description\fP"
.br
.ti -1c
.RI "\fBsetup\&.license\fP"
.br
.ti -1c
.RI "\fBsetup\&.url\fP"
.br
.ti -1c
.RI "\fBsetup\&.dependency_links\fP"
.br
.ti -1c
.RI "\fBsetup\&.install_requires\fP"
.br
.ti -1c
.RI "\fBsetup\&.packages\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
