.TH "simpletest" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simpletest
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBc_to_f\fP (c)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsensor\fP = MCP9808\&.MCP9808()"
.br
.ti -1c
.RI "\fBtemp\fP = sensor\&.readTempC()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def simpletest\&.c_to_f ( c)"

.SH "Variable Documentation"
.PP 
.SS "simpletest\&.sensor = MCP9808\&.MCP9808()"

.SS "simpletest\&.temp = sensor\&.readTempC()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
