.TH "drivers/TempSensor/Adafruit_Python_MCP9808/examples/simpletest.py" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drivers/TempSensor/Adafruit_Python_MCP9808/examples/simpletest.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsimpletest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsimpletest\&.c_to_f\fP (c)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsimpletest\&.sensor\fP = MCP9808\&.MCP9808()"
.br
.ti -1c
.RI "\fBsimpletest\&.temp\fP = sensor\&.readTempC()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
