.TH "lib/messages/spa/spa_data.h" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/messages/spa/spa_data.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <climits>\fP
.br
\fC#include <spa_message\&.h>\fP
.br
\fC#include <messages/op_codes\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSpaData< T >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
