.TH "lib/spa_communicator.cpp" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/spa_communicator.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'spa_communicator\&.hpp'\fP
.br
\fC#include 'messages/local/local_ack\&.h'\fP
.br
\fC#include 'messages/local/local_hello\&.h'\fP
.br
\fC#include 'messages/op_codes\&.h'\fP
.br
\fC#include 'messages/spa/spa_data\&.h'\fP
.br
\fC#include 'messages/spa/subscription_reply\&.h'\fP
.br
\fC#include 'messages/spa/subscription_request\&.h'\fP
.br
\fC#include <functional>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <memory>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
