.TH "lib/spa_message.h" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/spa_message.h
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include 'logical_address\&.h'\fP
.br
\fC#include 'messages/spa_header\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSpaMessage\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
