.TH "SpaCourier" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpaCourier
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <spa_courier\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpaCourier\fP (\fBLogicalAddress\fP destination, \fBLogicalAddress\fP source, ssize_t \fBfollowerSize\fP)"
.br
.ti -1c
.RI "\fBSpaCourier\fP (uint8_t version, uint8_t priority, uint16_t length, \fBLogicalAddress\fP destination, \fBLogicalAddress\fP source, uint16_t flags, ssize_t fS)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSpaMessage\fP \fBspaMessage\fP"
.br
.ti -1c
.RI "ssize_t \fBfollowerSize\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SpaCourier::SpaCourier (\fBLogicalAddress\fP destination, \fBLogicalAddress\fP source, ssize_t followerSize)\fC [inline]\fP"

.SS "SpaCourier::SpaCourier (uint8_t version, uint8_t priority, uint16_t length, \fBLogicalAddress\fP destination, \fBLogicalAddress\fP source, uint16_t flags, ssize_t fS)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "ssize_t SpaCourier::followerSize"

.SS "\fBSpaMessage\fP SpaCourier::spaMessage"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
