.TH "SpaLocalHeader" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpaLocalHeader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <spa_local_header\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpaLocalHeader\fP (uint16_t \fBsourcePort\fP, uint16_t \fBlength\fP, uint8_t \fBopcode\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBsourcePort\fP"
.br
.ti -1c
.RI "uint16_t \fBlength\fP"
.br
.ti -1c
.RI "uint8_t \fBopcode\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SpaLocalHeader::SpaLocalHeader (uint16_t sourcePort, uint16_t length, uint8_t opcode)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "uint16_t SpaLocalHeader::length"

.SS "uint8_t SpaLocalHeader::opcode"

.SS "uint16_t SpaLocalHeader::sourcePort"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
