.TH "drivers/subnetmanager/subnet_manager_driver.cpp" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drivers/subnetmanager/subnet_manager_driver.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./demo_addresses\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <local_communicator\&.hpp>\fP
.br
\fC#include <local_subnet_manager\&.hpp>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <messages/local/local_ack\&.h>\fP
.br
\fC#include <messages/local/local_spa_message\&.h>\fP
.br
\fC#include <messages/op_codes\&.h>\fP
.br
\fC#include <socket/serverSocket\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
