.TH "Subscriber" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Subscriber
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <component\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSubscriber\fP (\fBLogicalAddress\fP la, uint16_t d)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLogicalAddress\fP \fBsubscriberAddress\fP"
.br
.ti -1c
.RI "uint16_t \fBdeliveryRateDivisor\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Subscriber::Subscriber (\fBLogicalAddress\fP la, uint16_t d)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "uint16_t Subscriber::deliveryRateDivisor"

.SS "\fBLogicalAddress\fP Subscriber::subscriberAddress"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
