.TH "SubscriptionRequest" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SubscriptionRequest
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <subscription_request\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSubscriptionRequest\fP (\fBLogicalAddress\fP destination, \fBLogicalAddress\fP source, \fBLogicalAddress\fP mA)"
.br
.ti -1c
.RI "\fBSubscriptionRequest\fP (uint8_t version, uint8_t priority, \fBLogicalAddress\fP destination, \fBLogicalAddress\fP source, \fBLogicalAddress\fP mA, uint16_t flags, uint32_t lP, uint16_t dI, uint16_t dRD, uint8_t iI, uint8_t mI, uint8_t sP, uint8_t t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSpaMessage\fP \fBspaMessage\fP"
.br
.ti -1c
.RI "\fBLogicalAddress\fP \fBproducerAddr\fP"
.br
.ti -1c
.RI "\fBLogicalAddress\fP \fBconsumerAddr\fP"
.br
.ti -1c
.RI "\fBLogicalAddress\fP \fBmanagerAddr\fP"
.br
.ti -1c
.RI "uint32_t \fBleasePeriod\fP"
.br
.ti -1c
.RI "uint16_t \fBdialogId\fP"
.br
.ti -1c
.RI "uint16_t \fBdeliveryRateDivisor\fP"
.br
.ti -1c
.RI "uint8_t \fBinterfaceId\fP"
.br
.ti -1c
.RI "uint8_t \fBmessageId\fP"
.br
.ti -1c
.RI "uint8_t \fBsubscriptionPriority\fP"
.br
.ti -1c
.RI "uint8_t \fBtype\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SubscriptionRequest::SubscriptionRequest (\fBLogicalAddress\fP destination, \fBLogicalAddress\fP source, \fBLogicalAddress\fP mA)\fC [inline]\fP"

.SS "SubscriptionRequest::SubscriptionRequest (uint8_t version, uint8_t priority, \fBLogicalAddress\fP destination, \fBLogicalAddress\fP source, \fBLogicalAddress\fP mA, uint16_t flags, uint32_t lP, uint16_t dI, uint16_t dRD, uint8_t iI, uint8_t mI, uint8_t sP, uint8_t t)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBLogicalAddress\fP SubscriptionRequest::consumerAddr"

.SS "uint16_t SubscriptionRequest::deliveryRateDivisor"

.SS "uint16_t SubscriptionRequest::dialogId"

.SS "uint8_t SubscriptionRequest::interfaceId"

.SS "uint32_t SubscriptionRequest::leasePeriod"

.SS "\fBLogicalAddress\fP SubscriptionRequest::managerAddr"

.SS "uint8_t SubscriptionRequest::messageId"

.SS "\fBLogicalAddress\fP SubscriptionRequest::producerAddr"

.SS "\fBSpaMessage\fP SubscriptionRequest::spaMessage"

.SS "uint8_t SubscriptionRequest::subscriptionPriority"

.SS "uint8_t SubscriptionRequest::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
