.TH "drivers/TempSensor/TempSensor.cpp" 3 "Wed Oct 18 2017" "Version 1.2.0" "Cubium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drivers/TempSensor/TempSensor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./demo_addresses\&.hpp'\fP
.br
\fC#include <component\&.hpp>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'python2\&.7/Python\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCOMP_NAME\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCOMP_NAME\fP   TempSensor"
.br
.ti -1c
.RI "#define \fBCOMP_ADDR\fP   \fBla_TempSensor\fP"
.br
.ti -1c
.RI "#define \fBMNGR_ADDR\fP   \fBla_LSM\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COMP_ADDR   \fBla_TempSensor\fP"

.SS "#define \fBCOMP_NAME\fP   TempSensor"

.SS "#define MNGR_ADDR   \fBla_LSM\fP"

.SH "Function Documentation"
.PP 
.SS "int main (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cubium from the source code\&.
